[default]
save_path = './save'
n_jobs = 2
jobs_batch_size = 4
special_snes = [
    ZTF19aaqcqkv,
    ZTF19aadnxat,
    ZTF19aaripqw,
    ZTF20aavgmli,
    ZTF18adasisj,
    ZTF18aaqkdwf,
    ZTF18acqyvag,
    ZTF18acbudzh,
    ZTF19acxozhr,
    ZTF18abxbmqh,
    ZTF19aailltc,
    ZTF19aanijpu,
    ZTF19aaynsyd,
    ZTF19acbvpjn,
    ZTF18abuicad,
    ZTF19aanfnvl,
    ZTF19aavbkly,
    ZTF19acanzwg,
    ZTF20aauvbez,
    ZTF20aawmcrd,
    ZTF18adaslwa,
    ZTF20aaemtgw,
    ZTF20abfcshg,
    ZTF20aamuqwn,
    ZTF18ablqlzp,
    ZTF19acihlft,
    ZTF18abukavn,
    ZTF19acanzwg,
    ZTF19aclobbu,
]